### PR TITLE
No more hardcoded builtins ;)

### PR DESCRIPTION
**Pull request by hemanth**
All builtins for any version of `node`

### CODE REVIEW

**Comment by doowb** [comment]
I notice that library requires all of the builtins. Won't that make a performance impact? Also, you're returning an object instead of an Array.

I think doing... `exports.builtins = require('repl')._builtinLibs;` should be enough.

**Comment by jonschlinkert** [comment]
yeah I listed out the builtins to keep this fast, but I'm open to a pr. seems like https://www.npmjs.com/package/builtins would be lighter and faster, is there an advantage of all-builtins?

**Comment by hemanth** [comment]
@jonschlinkert Updated, my bad, should provide a `listing` option to `all-builtins` instead.
@doowb Yup, `all-builtins` would normally useful for demoing stuff.

**Comment by jonschlinkert** [comment]
no worries! I'll get this merged, or @doowb if you want you can if you get to it before me

**Comment by hemanth** [comment]
@jonschlinkert @doowb :cat:

**Comment by hemanth** [comment]
Thanks!

**Pull request merged**
